### ISSUE TITLE
still cant load the mod

### ISSUE THREAD

**Issue by Falafelrollo** [sapphiriza/FactorioMod_FlowConfig#1]
![image](https://github.com/sapphiriza/FactorioMod_FlowConfig/assets/35108510/1e42e423-4ca2-4351-81fb-5dbbfcb958d4)
after i disabled underwater pipes still got this error

playing a pyBlock run here is the save
[PyBlock[item=py-construction-robot-01][item=clay-pit-mk04]3.zip](https://github.com/sapphiriza/FactorioMod_FlowConfig/files/12856872/PyBlock.item.py-construction-robot-01.item.clay-pit-mk04.3.zip)

**Comment by DrWiFi** [comment]
Hello,
I'm getting a couple similar issues:
When underwater pipes enabled:
<img width="558" alt="Screenshot 2023-10-10 at 8 59 53 AM" src="https://github.com/sapphiriza/FactorioMod_FlowConfig/assets/50341031/932b20ff-59fb-4fdb-942b-29e6b39799f3">

With underwater pipes not enabled:
<img width="1032" alt="Screenshot 2023-10-10 at 8 56 00 AM" src="https://github.com/sapphiriza/FactorioMod_FlowConfig/assets/50341031/655fea0f-53d1-4b08-9747-7cdea867d03d">

If I disable Flow Control the rest of the mods load properly
Thanks!

**Comment by sapphiriza** [comment]
Thank you both for the info! These are both very helpful, I'll investigate a fix tonight.

**Comment by sapphiriza** [comment]
Submitted a potential fix for 1.0.5, please let me know if that doesn't work for either of you!

**Comment by DrWiFi** [comment]
With underwater pipes enabled I still get this:
<img width="558" alt="Screenshot 2023-10-10 at 2 37 33 PM" src="https://github.com/sapphiriza/FactorioMod_FlowConfig/assets/50341031/fbaa7cc8-6bd2-4d60-95ae-0f8c3ad3cfa0">

But disabling UWPs allows it to load.
Thanks!

**Comment by sapphiriza** [comment]
If you add underwater-pipe-placer to the mod settings denylist (Settings > Mod Settings > Flow Configuration > Pipe prefix denylist), that does fix underwater pipes!
![image](https://github.com/sapphiriza/FactorioMod_FlowConfig/assets/120682601/79cb6472-d653-4d3d-afd9-5b97507333aa)
I'll update the mod to include this by default in the next version, since fixing this yourself unfortunately requires disabling the conflicting mod, re-enabling Flow Config, changing the setting, and then re-enabling the conflicting mod.

I'm going to close this issue, but if you have other mods that cause problems, feel free to let me know in another issue! Cheers ♥
